Importando a biblioteca "pandas" com o nome de "pd" para poder carregar o arquivo de dados

In [2]:
import pandas as pd

Adicionando um dataset/dataframe as "df"

In [3]:
df = pd.read_excel('default_of_credit_card_clients__courseware_version_1_21_19.xls')

Examinando o numero de linhas e colunas

In [4]:
df.shape

(30000, 25)

Informação sobre todas as colunas

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 25 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   ID                          30000 non-null  str
 1   LIMIT_BAL                   30000 non-null  int64
 2   SEX                         30000 non-null  int64
 3   EDUCATION                   30000 non-null  int64
 4   MARRIAGE                    30000 non-null  int64
 5   AGE                         30000 non-null  int64
 6   PAY_1                       30000 non-null  object
 7   PAY_2                       30000 non-null  int64
 8   PAY_3                       30000 non-null  int64
 9   PAY_4                       30000 non-null  int64
 10  PAY_5                       30000 non-null  int64
 11  PAY_6                       30000 non-null  int64
 12  BILL_AMT1                   30000 non-null  int64
 13  BILL_AMT2                   30000 non-null  int64
 14  BILL_AMT3                   30000 non-null  int64
 15  BILL_AMT4                   30000 non-null  int64
 16  BILL_AMT5                   30000 non-null  int64
 17  BILL_AMT6                   30000 non-null  int64
 18  PAY_AMT1                    30000 non-null  int64
 19  PAY_AMT2                    30000 non-null  int64
 20  PAY_AMT3                    30000 non-null  int64
 21  PAY_AMT4                    30000 non-null  int64
 22  PAY_AMT5                    30000 non-null  int64
 23  PAY_AMT6                    30000 non-null  int64
 24  default payment next month  30000 non-null  int64
dtypes: int64(23), object(1), str(1)
memory usage: 5.7+ MB

Mostra as primeiras linhas do Dataframe, respectivamente.

In [6]:
df.head()

,ID,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_1,PAY_2,PAY_3,PAY_4,...,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6,default payment next month
0,798fc410-45c1,20000,2,2,1,24,2,2,-1,-1,...,0,0,0,0,689,0,0,0,0,1
1,8a8c8f3b-8eb4,120000,2,2,2,26,-1,2,0,0,...,3272,3455,3261,0,1000,1000,1000,0,2000,1
2,85698822-43f5,90000,2,2,2,34,0,0,0,0,...,14331,14948,15549,1518,1500,1000,1000,1000,5000,0
3,0737c11b-be42,50000,2,2,1,37,0,0,0,0,...,28314,28959,29547,2000,2019,1200,1100,1069,1000,0
4,3b7f77cc-dbc0,50000,1,2,1,57,-1,0,-1,0,...,20940,19146,19131,2000,36681,10000,9000,689,679,0

Empresa de Cartão de crédito
Dataframe com 3000 clientes. 

Definição de Linha: Cada linha é um cliente.

Objetivo: Prever se algum cliente ficará Inadiplente no proximo mes

In [7]:
df.columns

Index(['ID', 'LIMIT_BAL', 'SEX', 'EDUCATION', 'MARRIAGE', 'AGE', 'PAY_1',
       'PAY_2', 'PAY_3', 'PAY_4', 'PAY_5', 'PAY_6', 'BILL_AMT1', 'BILL_AMT2',
       'BILL_AMT3', 'BILL_AMT4', 'BILL_AMT5', 'BILL_AMT6', 'PAY_AMT1',
       'PAY_AMT2', 'PAY_AMT3', 'PAY_AMT4', 'PAY_AMT5', 'PAY_AMT6',
       'default payment next month'],
      dtype='str')

ID = id, LIMIT_BAL = Valor do crédito, SEX = 1.Masculino / 2.Feminino, EDUCATION = 1.pós-graduacao/2.universidade/3.ensinoMedio/4.Outros

MARRIAGE = 1.Casado/2.Solteiro/3.Outros, AGE = idade (ano), PAY_1-PAY_6 = Registro de pagamentos mensais passados (PAY_1 representa o status de reeembolso no mes anterior.)

PAY_1-PAY6 = escala de pagamento de reembolso: (-1.PagamentoPontual, 1.Atraso um mês, 2.Atraso dois meses, ..., 9.atraso de nove ou mais.)

BILL_AMT1-BILL_AMT6 = Valor da fatura, PAY_AMT1-PAY_AMT6 = Valor de pagamentos anteriores.

----------------------------------------------------

Verificando valores exclusivos

In [8]:
df['ID'].unique()

<StringArray>
['798fc410-45c1', '8a8c8f3b-8eb4', '85698822-43f5', '0737c11b-be42',
 '3b7f77cc-dbc0', 'ceae2946-47e4', 'd3b8ce26-9c89', 'd6e1911b-54d0',
 '8421d3b3-2b54', '62a2fd79-cd90',
 ...
 '33170a20-8592', '46c706d6-6aef', '4849f25c-3f1f', '62c53ee3-f0cf',
 '67697c15-2247', 'ecff42d0-bdc6', '99d1fa0e-222b', '95cdd3e7-4f24',
 '00d03f02-04cd', '15d69f9f-5ad3']
Length: 29687, dtype: str

In [9]:
df.shape

(30000, 25)

Quantidade de IDs não bate com a quantidade de linhas

Verificar se temos duplicatas, contas repetidas.

In [10]:
id_counts = df['ID'].value_counts() 
id_counts.head()

ID
26bde6da-f148    2
42009c72-651f    2
73ed1381-3a3f    2
4f95b36b-ab10    2
8d3a2576-a958    2
Name: count, dtype: int64

In [11]:
id_counts.value_counts()

count
1    29374
2      313
Name: count, dtype: int64

MASCARA BOOLEANA

Método para filtrar um array, ou série, obedecendo uma condição

In [12]:
dupe_mask = id_counts == 2
dupe_mask[0:5]

ID
26bde6da-f148    True
42009c72-651f    True
73ed1381-3a3f    True
4f95b36b-ab10    True
8d3a2576-a958    True
Name: count, dtype: bool

In [13]:
id_counts.index[0:5]

Index(['26bde6da-f148', '42009c72-651f', '73ed1381-3a3f', '4f95b36b-ab10',
       '8d3a2576-a958'],
      dtype='str', name='ID')

In [14]:
dupe_ids = id_counts.index[dupe_mask]

Alteramos a variável dupe_ids para uma lista

In [15]:
dupe_ids = list(dupe_ids)
len(dupe_ids)

313

In [16]:
dupe_ids[0:5]

['26bde6da-f148',
 '42009c72-651f',
 '73ed1381-3a3f',
 '4f95b36b-ab10',
 '8d3a2576-a958']

Filtrando o Dataframe para visualizar as colunas dos 3 primeiros IDs duplicados

In [17]:
df.loc[df['ID'].isin(dupe_ids[0:3]),:].head(10)

,ID,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_1,PAY_2,PAY_3,PAY_4,...,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6,default payment next month
141,26bde6da-f148,180000,1,2,2,28,-1,-1,-1,-1,...,332,416,416,0,416,332,500,3500,832,0
196,42009c72-651f,150000,2,2,1,34,-2,-2,-2,-2,...,116,0,1500,0,0,116,0,1500,0,0
241,26bde6da-f148,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
296,42009c72-651f,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
323,73ed1381-3a3f,230000,2,2,1,28,0,0,0,-2,...,2100,767,6173,1710,1100,1000,767,6173,1000,1
423,73ed1381-3a3f,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

Criando uma matriz booleana com o mesmo tamanho do Dataframe inteiro, usando a condição "é igual a zero"

In [18]:
df_zero_mask = df == 0

Criando uma série booleana que identifique cada linha em que todos  os elementos a partir  da segunda coluna sejam 0.

In [19]:
feature_zero_mask = df_zero_mask.iloc[:,1:].all(axis=1)

In [20]:
sum(feature_zero_mask)

315

Limpando o Dataframe, eliminando as linhas com zeros, exceto pelo ID

In [21]:
df_clean_1 = df.loc[~feature_zero_mask,:].copy()

In [22]:
df_clean_1.shape

(29685, 25)

In [24]:
df_clean_1['ID'].nunique()

29685